name: iban
description: A validation library for ibans
version: 0.1.1
authors:
- Christian Loitsch <christian@loitsch.com>
- Harm Aarts <harm@aarts.email>
homepage: https://github.com/close2/iban

environment:
  sdk: '>=1.0.0 <3.0.0'

dependencies:
  mod97: '>=0.0.1 <1.0.0'

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
